if not exist files\labs\pembentukan_karakter_taqwa_Low.flv echo pembentukan_karakter_taqwa_Low.flv >> vip.txt
if not exist files\labs\perenungan_dan_motivasi.FLV echo perenungan_dan_motivasi.FLV >> vip.txt
if not exist files\labs\KESADARAN_DIRI.mp4 echo KESADARAN_DIRI.mp4 >> vip.txt
if not exist files\labs\menentukan-isi-petunjuk-kerja-bagian-2.flv echo menentukan-isi-petunjuk-kerja-bagian-2.flv >> vip.txt
if not exist files\labs\menentukan-isi-petunjuk-kerja-bagian-3.flv echo menentukan-isi-petunjuk-kerja-bagian-3.flv >> vip.txt
if not exist files\labs\menentukan-isi-petunjuk-kerja-bagian-4.flv echo menentukan-isi-petunjuk-kerja-bagian-4.flv >> vip.txt
if not exist files\labs\menentukan-jenis-karangan-dan-pengembangan-karangan-seg1.flv echo menentukan-jenis-karangan-dan-pengembangan-karangan-seg1.flv >> vip.txt
if not exist files\labs\menentukan-jenis-karangan-dan-pengembangan-karangan-seg2.flv echo menentukan-jenis-karangan-dan-pengembangan-karangan-seg2.flv >> vip.txt
if not exist files\labs\menentukan-jenis-karangan-dan-pengembangan-karangan-seg3.flv echo menentukan-jenis-karangan-dan-pengembangan-karangan-seg3.flv >> vip.txt
if not exist files\labs\menentukan-kalimat-efektif-penjelas-bagian-1.flv echo menentukan-kalimat-efektif-penjelas-bagian-1.flv >> vip.txt
if not exist files\labs\menentukan-kalimat-efektif-penjelas-bagian-2.flv echo menentukan-kalimat-efektif-penjelas-bagian-2.flv >> vip.txt
if not exist files\labs\menentukan-kalimat-efektif-penjelas-bagian-3.flv echo menentukan-kalimat-efektif-penjelas-bagian-3.flv >> vip.txt
if not exist files\labs\menentukan-kalimat-kritikesai-dan-resensi-bagian-1.flv echo menentukan-kalimat-kritikesai-dan-resensi-bagian-1.flv >> vip.txt
if not exist files\labs\menentukan-kalimat-kritikesai-dan-resensi-bagian-2.flv echo menentukan-kalimat-kritikesai-dan-resensi-bagian-2.flv >> vip.txt
if not exist files\labs\menentukan-kalimat-kritikesai-dan-resensi-bagian-3.flv echo menentukan-kalimat-kritikesai-dan-resensi-bagian-3.flv >> vip.txt
if not exist files\labs\menentukan-kalimat-kritikesai-dan-resensi-bagian-4.flv echo menentukan-kalimat-kritikesai-dan-resensi-bagian-4.flv >> vip.txt
if not exist files\labs\paragraf-bagian-1.flv echo paragraf-bagian-1.flv >> vip.txt
if not exist files\labs\paragraf-bagian-2.flv echo paragraf-bagian-2.flv >> vip.txt
if not exist files\labs\paragraf-bagian-3.flv echo paragraf-bagian-3.flv >> vip.txt
if not exist files\labs\paragraf-bagian-4.flv echo paragraf-bagian-4.flv >> vip.txt
if not exist files\labs\giving-advice-_you-should-take-a-rest_-seg1.flv echo giving-advice-_you-should-take-a-rest_-seg1.flv >> vip.txt
if not exist files\labs\giving-advice-_you-should-take-a-rest_-seg2.flv echo giving-advice-_you-should-take-a-rest_-seg2.flv >> vip.txt
if not exist files\labs\giving-advice-_you-should-take-a-rest_-seg3.flv echo giving-advice-_you-should-take-a-rest_-seg3.flv >> vip.txt
if not exist files\labs\the-word-means-bagian-1.flv echo the-word-means-bagian-1.flv >> vip.txt
if not exist files\labs\the-word-means-bagian-2.flv echo the-word-means-bagian-2.flv >> vip.txt
if not exist files\labs\the-word-means-bagian-3.flv echo the-word-means-bagian-3.flv >> vip.txt
if not exist files\labs\whould-you-like-to-have-dinner-seg1.flv echo whould-you-like-to-have-dinner-seg1.flv >> vip.txt
if not exist files\labs\whould-you-like-to-have-dinner-seg2.flv echo whould-you-like-to-have-dinner-seg2.flv >> vip.txt
if not exist files\labs\whould-you-like-to-have-dinner-seg3.flv echo whould-you-like-to-have-dinner-seg3.flv >> vip.txt
if not exist files\labs\jaringan-tumbuhan-berdasarkan-struktur-sel-seg1.flv echo jaringan-tumbuhan-berdasarkan-struktur-sel-seg1.flv >> vip.txt
if not exist files\labs\jaringan-tumbuhan-berdasarkan-struktur-sel-seg2.flv echo jaringan-tumbuhan-berdasarkan-struktur-sel-seg2.flv >> vip.txt
if not exist files\labs\jaringan-tumbuhan-berdasarkan-struktur-sel-seg3.flv echo jaringan-tumbuhan-berdasarkan-struktur-sel-seg3.flv >> vip.txt
if not exist files\labs\mendiskripsikan-sistem-peredaran-darah-manusia-seg1.flv echo mendiskripsikan-sistem-peredaran-darah-manusia-seg1.flv >> vip.txt
if not exist files\labs\mendiskripsikan-sistem-peredaran-darah-manusia-seg2.flv echo mendiskripsikan-sistem-peredaran-darah-manusia-seg2.flv >> vip.txt
if not exist files\labs\mendiskripsikan-sistem-peredaran-darah-manusia-seg3.flv echo mendiskripsikan-sistem-peredaran-darah-manusia-seg3.flv >> vip.txt
if not exist files\labs\mengidentifikasi-struktur-dan-fungsi-organel-sel-bagian-1.flv echo mengidentifikasi-struktur-dan-fungsi-organel-sel-bagian-1.flv >> vip.txt
if not exist files\labs\mengidentifikasi-struktur-dan-fungsi-organel-sel-bagian-2.flv echo mengidentifikasi-struktur-dan-fungsi-organel-sel-bagian-2.flv >> vip.txt
if not exist files\labs\mengidentifikasi-struktur-dan-fungsi-organel-sel-bagian-3.flv echo mengidentifikasi-struktur-dan-fungsi-organel-sel-bagian-3.flv >> vip.txt
if not exist files\labs\mengidentifikasi-struktur-dan-fungsi-organel-sel-bagian-4.flv echo mengidentifikasi-struktur-dan-fungsi-organel-sel-bagian-4.flv >> vip.txt
if not exist files\labs\metabolisme-bagian-1.flv echo metabolisme-bagian-1.flv >> vip.txt
if not exist files\labs\metabolisme-bagian-2.flv echo metabolisme-bagian-2.flv >> vip.txt
if not exist files\labs\metabolisme-bagian-3.flv echo metabolisme-bagian-3.flv >> vip.txt
if not exist files\labs\metabolisme-bagian-4.flv echo metabolisme-bagian-4.flv >> vip.txt
if not exist files\labs\sintesis-protein-bagian-1.flv echo sintesis-protein-bagian-1.flv >> vip.txt
if not exist files\labs\sintesis-protein-bagian-2.flv echo sintesis-protein-bagian-2.flv >> vip.txt
if not exist files\labs\sintesis-protein-bagian-3.flv echo sintesis-protein-bagian-3.flv >> vip.txt
if not exist files\labs\unggul-dengan-bioteknologi-seg-1.flv echo unggul-dengan-bioteknologi-seg-1.flv >> vip.txt
if not exist files\labs\unggul-dengan-bioteknologi-seg-2.flv echo unggul-dengan-bioteknologi-seg-2.flv >> vip.txt
if not exist files\labs\unggul-dengan-bioteknologi-seg-3.flv echo unggul-dengan-bioteknologi-seg-3.flv >> vip.txt
if not exist files\labs\Motivasi_dan_Inspirasi.mp4 echo Motivasi_dan_Inspirasi.mp4 >> vip.txt
if not exist files\labs\keruntuhan_evolusi_darwin_1.mp4 echo keruntuhan_evolusi_darwin_1.mp4 >> vip.txt
if not exist files\labs\koperasi-bagian-1.flv echo koperasi-bagian-1.flv >> vip.txt
if not exist files\labs\koperasi-bagian-2.flv echo koperasi-bagian-2.flv >> vip.txt
if not exist files\labs\koperasi-bagian-3.flv echo koperasi-bagian-3.flv >> vip.txt
if not exist files\labs\koperasi-bagian-4.flv echo koperasi-bagian-4.flv >> vip.txt
if not exist files\labs\pendapatan-nasional-bagian-1.flv echo pendapatan-nasional-bagian-1.flv >> vip.txt
if not exist files\labs\pendapatan-nasional-bagian-2.flv echo pendapatan-nasional-bagian-2.flv >> vip.txt
if not exist files\labs\pendapatan-nasional-bagian-3.flv echo pendapatan-nasional-bagian-3.flv >> vip.txt
if not exist files\labs\perilaku-produsen-dan-konsumen-bagian-1.flv echo perilaku-produsen-dan-konsumen-bagian-1.flv >> vip.txt
if not exist files\labs\perilaku-produsen-dan-konsumen-bagian-2.flv echo perilaku-produsen-dan-konsumen-bagian-2.flv >> vip.txt
if not exist files\labs\perilaku-produsen-dan-konsumen-bagian-3.flv echo perilaku-produsen-dan-konsumen-bagian-3.flv >> vip.txt
if not exist files\labs\perilaku-produsen-dan-konsumen-bagian-4.flv echo perilaku-produsen-dan-konsumen-bagian-4.flv >> vip.txt
if not exist files\labs\Keindahan_Molekul_Air_Zam_Zam.mp4 echo Keindahan_Molekul_Air_Zam_Zam.mp4 >> vip.txt
if not exist files\labs\kehebatan_Allah_saintifik_lebah.mp4 echo kehebatan_Allah_saintifik_lebah.mp4 >> vip.txt
if not exist files\labs\Hakikat_Penciptaan_Manusia.mp4 echo Hakikat_Penciptaan_Manusia.mp4 >> vip.txt
if not exist files\labs\FAKTA_PENCIPTAAN_1_40.flv echo FAKTA_PENCIPTAAN_1_40.flv >> vip.txt
if not exist files\labs\NOKIA_MASA_DEPAN_NOKIA_FUTURE_VISION.mp4 echo NOKIA_MASA_DEPAN_NOKIA_FUTURE_VISION.mp4 >> vip.txt
if not exist files\labs\masuknya_Jepang.WMV echo masuknya_Jepang.WMV >> vip.txt
if not exist files\labs\Kreasi_Unik_Kerajinan_Daun_Kelapa_High.flv echo Kreasi_Unik_Kerajinan_Daun_Kelapa_High.flv >> vip.txt
if not exist files\labs\kerajinan_tangan_kreatif_High.flv echo kerajinan_tangan_kreatif_High.flv >> vip.txt
if not exist files\labs\kerajinan_tangan_kotak_pensil1_avi_Low.flv echo kerajinan_tangan_kotak_pensil1_avi_Low.flv >> vip.txt
if not exist files\labs\kerajinan_kaca_pyrex_Low.flv echo kerajinan_kaca_pyrex_Low.flv >> vip.txt
if not exist files\labs\Kerajinan_Batok_Kelapa_High.flv echo Kerajinan_Batok_Kelapa_High.flv >> vip.txt
if not exist files\labs\hiasan_rumah_kerajinan_tangan_High.flv echo hiasan_rumah_kerajinan_tangan_High.flv >> vip.txt
if not exist files\labs\Irian_Jaya_Fighting_for_W_Papuan_Independence_Indonesia.avi echo Irian_Jaya_Fighting_for_W_Papuan_Independence_Indonesia.avi >> vip.txt
if not exist files\labs\FAKTA_PENCIPTAAN_4_4.flv echo FAKTA_PENCIPTAAN_4_4.flv >> vip.txt
if not exist files\labs\FAKTA_PENCIPTAAN_2_4.flv echo FAKTA_PENCIPTAAN_2_4.flv >> vip.txt
if not exist files\labs\FAKTA_PENCIPTAAN_3_4.flv echo FAKTA_PENCIPTAAN_3_4.flv >> vip.txt
if not exist files\labs\FAKTA_PENCIPTAAN_1_4.flv echo FAKTA_PENCIPTAAN_1_4.flv >> vip.txt
if not exist files\labs\bosan_hidup_biasa_biasa_saja.FLV echo bosan_hidup_biasa_biasa_saja.FLV >> vip.txt
if not exist files\labs\Pakta_seputar_proklamasi.avi echo Pakta_seputar_proklamasi.avi >> vip.txt
if not exist files\labs\Drs_Muhammad_Hatta.avi echo Drs_Muhammad_Hatta.avi >> vip.txt
if not exist files\labs\Candi_candi_di_Jawa_Tengah_dan_Jawa_Timur_YouTube.mp4 echo Candi_candi_di_Jawa_Tengah_dan_Jawa_Timur_YouTube.mp4 >> vip.txt
if not exist files\labs\bahan_kimia_bagian_2.flv echo bahan_kimia_bagian_2.flv >> vip.txt
if not exist files\labs\mendeskripsikan-wilayah-pewilayahan-di-dunia-bagian-1.flv echo mendeskripsikan-wilayah-pewilayahan-di-dunia-bagian-1.flv >> vip.txt
if not exist files\labs\mendeskripsikan-wilayah-pewilayahan-di-dunia-bagian-2.flv echo mendeskripsikan-wilayah-pewilayahan-di-dunia-bagian-2.flv >> vip.txt
if not exist files\labs\mendeskripsikan-wilayah-pewilayahan-di-dunia-bagian-3.flv echo mendeskripsikan-wilayah-pewilayahan-di-dunia-bagian-3.flv >> vip.txt
if not exist files\labs\mendeskripsikan-wilayah-pewilayahan-di-dunia-bagian-4.flv echo mendeskripsikan-wilayah-pewilayahan-di-dunia-bagian-4.flv >> vip.txt
if not exist files\labs\sumber-daya-alam-bagian-1.flv echo sumber-daya-alam-bagian-1.flv >> vip.txt
if not exist files\labs\sumber-daya-alam-bagian-2.flv echo sumber-daya-alam-bagian-2.flv >> vip.txt
if not exist files\labs\sumber-daya-alam-bagian-3.flv echo sumber-daya-alam-bagian-3.flv >> vip.txt
if not exist files\labs\gejala_listrik_statis_bagian_2.flv echo gejala_listrik_statis_bagian_2.flv >> vip.txt
if not exist files\labs\gejala_listrik_statis_bagian_1.flv echo gejala_listrik_statis_bagian_1.flv >> vip.txt
if not exist files\labs\balada_si_monas.flv echo balada_si_monas.flv >> vip.txt
if not exist files\labs\menu_sehat.flv echo menu_sehat.flv >> vip.txt
if not exist files\labs\melengkapi_pantun_bagian_2.flv echo melengkapi_pantun_bagian_2.flv >> vip.txt
if not exist files\labs\melengkapi_pantun_bagian_1.flv echo melengkapi_pantun_bagian_1.flv >> vip.txt
if not exist files\labs\sel-elektrokimia-bagian-1.flv echo sel-elektrokimia-bagian-1.flv >> vip.txt
if not exist files\labs\sel-elektrokimia-bagian-2.flv echo sel-elektrokimia-bagian-2.flv >> vip.txt
if not exist files\labs\sel-elektrokimia-bagian-3.flv echo sel-elektrokimia-bagian-3.flv >> vip.txt
if not exist files\labs\menggunakan-aturan-pada-bentuk-akar-seg1.flv echo menggunakan-aturan-pada-bentuk-akar-seg1.flv >> vip.txt
if not exist files\labs\menggunakan-aturan-pada-bentuk-akar-seg2.flv echo menggunakan-aturan-pada-bentuk-akar-seg2.flv >> vip.txt
if not exist files\labs\menggunakan-aturan-pada-bentuk-akar-seg3.flv echo menggunakan-aturan-pada-bentuk-akar-seg3.flv >> vip.txt
if not exist files\labs\perkalian-matriks.flv echo perkalian-matriks.flv >> vip.txt
if not exist files\labs\persamaan-lingkaran-bagian-1.flv echo persamaan-lingkaran-bagian-1.flv >> vip.txt
if not exist files\labs\persamaan-lingkaran-bagian-2.flv echo persamaan-lingkaran-bagian-2.flv >> vip.txt
if not exist files\labs\persamaan-lingkaran-bagian-3.flv echo persamaan-lingkaran-bagian-3.flv >> vip.txt
if not exist files\labs\persamaan-lingkaran-bagian-4.flv echo persamaan-lingkaran-bagian-4.flv >> vip.txt
if not exist files\labs\ruang-sample.flv echo ruang-sample.flv >> vip.txt
